version: 2

# Specify os and python version
build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
    nodejs: "20"
  commands:
    - pip install uv
    - uv run python -m sphinx docs $READTHEDOCS_OUTPUT/html -b html -W

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py