# Read the Docs French Configuration
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install --upgrade pip setuptools wheel
      - pip install -r docs/requirements.txt

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/conf_fr.py
  fail_on_warning: false

formats:
  - pdf
  - epub

search:
  ranking:
    api.rst: 2
    tutorial.rst: 3
    userguide.rst: 3
  ignore:
    - locale/
    - _build/
