language: node_js
node_js: "18"
python: "3.12"

branches:
  only:
    - master
    - devrev-final
    - develop

cache:
  directories:
    - node_modules
    - client/node_modules
    - ~/.cache/pip

env:
  - NODE_ENV=development

before_install:
  - python3 --version
  - pip3 --version
  - node --version
  - npm --version

install:
  # Install Python dependencies
  - pip3 install -r requirements.txt
  - pip3 install -r docs/requirements.txt
  # Install Node.js dependencies
  - npm ci
  - cd client && npm ci && cd ..

before_script:
  # Lint Python code
  - python3 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
  # Lint JavaScript/React code
  - cd client && npm run lint:check || true && cd ..

script:
  # Test Python components
  - python3 -m pytest --version || echo "No pytest tests configured"
  # Test React application
  - cd client && npm run test:ci || npm test -- --coverage --watchAll=false && cd ..
  # Build the application
  - cd client && npm run build && cd ..
  # Validate locale files
  - python3 -c "import json; [json.load(open(f'client/locales/{lang}.json')) for lang in ['en', 'fr', 'es', 'pt']]"

after_success:
  - echo "Build completed successfully"

notifications:
  email:
    on_success: change
    on_failure: always
