[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "amrnet"
version = "1.0.2"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [{name = "Louise Cerdeira", email = "lcerdeira@gmail.com}]
authors = [{name = "Vandana Sharma", email = "}]

classifiers = [
    "License :: GNU General Public License v3 (GPLv3)",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Intended Audience :: Science/Research"
]

[project.urls]
homepage = "https://www.amrnet.org/"
documentation = "https://amrnet.readthedocs.io/"
repository = "https://github.com/amrnet/amrnet/"