[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "amrnet"
authors = [{name = "Louise", email = "lcerdeira@gmail.com}]
dynamic = ["version", "description"]
