name: AMRNet Chatbot

on:
  issue_comment:
    types: [created]

jobs:
  chatbot_response:
    runs-on: ubuntu-latest
    if: | # Only run if the comment is new and starts with @amr-bot
      github.event.action == 'created' &&
      startsWith(github.event.comment.body, '@amr-bot')
    steps:
      - name: Checkout repository # To access files if needed later
        uses: actions/checkout@v4
        with:
          repository: amrnet/amrnet # Checkout the amrnet/amrnet repo
          ref: ${{ github.event.issue.pull_request && github.event.issue.pull_request.head.sha || github.ref }} # Fixed logical OR for refs
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai PyGithub

      - name: Run Chatbot Logic
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_ID: ${{ github.event.comment.id }} # To potentially react to the comment
          REPO_FULL_NAME: ${{ github.repository }} # e.g., amrnet/amrnet
        run: python .github/scripts/chatbot_handler.py
