name: ESLint

on:
  push:
    branches: [ "devrev", "main" ]
  pull_request:
    branches: [ "devrev", "main" ]
  schedule:
    - cron: '43 17 * * 1'

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint
        id: run_eslint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint . \
            --config .eslintrc.js \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif
        # Removed 'continue-on-error: true' here
        # This will make the workflow fail immediately if eslint errors

      - name: Check if SARIF file exists (for debugging)
        # This step will only run if 'Run ESLint' succeeds.
        # If 'Run ESLint' fails, the workflow will stop before this.
        run: |
          ls -la eslint-results.sarif || echo "eslint-results.sarif does NOT exist, as 'Run ESLint' must have failed."
        # Keep continue-on-error: true here, as this is just a diagnostic step

      - name: Upload analysis results to GitHub
        # This step will only run if 'Run ESLint' succeeded and created the file.
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
