name: Translate Web App Strings

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - staging # Or your main development branch
    paths:
      - 'locales/en.json' # Trigger only if the source English file changes

jobs:
  translate_strings:
    runs-on: ubuntu-latest
    # --- IMPORTANT FIX: Add permissions for the GitHub Token ---
    permissions:
      contents: write # Needed to create/commit files for the PR
      pull-requests: write # Needed to create the pull request
    # -----------------------------------------------------------
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # If creating a PR with peter-evans/create-pull-request,
          # this checkout step often needs a token that has write permissions.
          # The default GITHUB_TOKEN (with job-level permissions) is usually sufficient.
          # token: ${{ secrets.GH_PAT }} # Uncomment if using a Personal Access Token with broader scope

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai PyGithub # PyGithub for PR creation if needed

      - name: Run Translation Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # GITHUB_TOKEN is automatically provided with permissions defined above
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_FULL_NAME: ${{ github.repository }} # Correct way to get owner/repo name
        run: python .github/scripts/translator.py

      - name: Create Pull Request or Commit Changes
        uses: peter-evans/create-pull-request@v6
        with:
          # Uses the GITHUB_TOKEN (with enhanced permissions) or a specific GH_PAT if provided
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          commit-message: "feat: Add/Update translations from 'en.json'"
          branch: "chore/auto-translations" # Name of the branch to create
          delete-branch: true
          title: "Automated Translations Update"
          body: |
            Automated translations generated based on changes to `locales/en.json`.
            Please review the changes.

            Target Languages: French, Spanish, Portuguese, German, Italian, Japanese, Chinese.
          labels: "translation, i18n, automated"
          assignees: "${{ github.actor }}" # Assign PR to the person who triggered the workflow (e.g., via push)
          # Add other options as needed, e.g., reviewers